/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game;

import static org.junit.Assert.assertNotNull;
import static org.mockito.Mockito.*;

import org.junit.Test;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();

        App mockTest = mock(App.class);
        when(mockTest.getGreeting()).thenReturn("Hello");

        assertNotNull("app should have a greeting", mockTest.getGreeting());
    }
}
